###############################################
# Stiebel Eltron Heat Pump Control - Controls Configuration
# Configuration for interactive controls that can change heat pump settings
###############################################

controls:  
  # Mode controls
  program_switch:
    type: select
    name: Heat Pump Operating Mode
    can_member: MANAGER
    write_signal: ACTIVE_HEATING_PROGRAM
    options:
      - Emergency
      - Standby
      - Automatic
      - Day mode
      - Night mode
      - Summer mode
      - Off
    icon: mdi:tune-vertical
    
  # Temperature controls
  day_temp:
    type: number
    name: Target Temperature
    can_member: MANAGER
    write_signal: ROOM_SET_TEMP_I
    min: 12
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
    icon: mdi:thermometer

  night_temp:
    type: number
    name: Target Temperature
    can_member: MANAGER
    write_signal: ROOM_SET_TEMP_NIGHT
    min: 12
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
    icon: mdi:thermometer

  # Button controls
  update_time:
    type: button
    name: Update Heat Pump Time
    icon: mdi:clock-outline
    action_type: system_time
    can_member: MANAGER
    
  # reset_error:
  #   type: button
  #   name: Reset Error State
  #   icon: mdi:alert-circle-outline
  #   action_type: reset_error
  #   can_member: MANAGER
  #     actions:
  #       - type: write_signal
  #         signal: HOUR
  #         can_member: MANAGER
  #         value: "${%H}"  # Current hour
  #         delay: 0.5
  #       - type: write_signal
  #         signal: MINUTE
  #         can_member: MANAGER
  #         value: "${%M}"  # Current minute
  #         delay: 0.5
  #       - type: write_signal
  #         signal: DAY
  #         can_member: MANAGER
  #         value: "${%d}"  # Current day
  #         delay: 0.5
  #       - type: write_signal
  #         signal: MONTH
  #         can_member: MANAGER
  #         value: "${%m}"  # Current month
  #         delay: 0.5
  #       - type: write_signal
  #         signal: YEAR
  #         can_member: MANAGER
  #         value: "${%Y}"  # Current year
